apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radicale
  name: radicale
  namespace: radicale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radicale
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: radicale
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - image: ghcr.io/kozea/radicale:stable
          name: radicale
          ports:
            - containerPort: 5232
          volumeMounts:
          - name: data
            mountPath: /var/lib/radicale
          - name: config
            mountPath: /etc/radicale
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radicale-config
      - name: data
        persistentVolumeClaim:
          claimName: radicale-data
      restartPolicy: Always