apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radicale
  name: radicale
  namespace: radicale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radicale
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: radicale
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - image: ghcr.io/kozea/radicale:stable
          name: radicale
          ports:
            - containerPort: 5232
          volumeMounts:
          - name: data
            mountPath: /var/lib/radicale
          - name: config
            mountPath: /etc/radicale/config
            subPath: config
        - image: nginx:alpine
          name: radicale-proxy
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: radicale-data
      - name: config
        configMap:
          name: radicale-config
      restartPolicy: Always 