apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calcom
  name: calcom
  namespace: calcom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calcom
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: calcom
    spec:
      containers:
        - image: calcom/cal.com:latest
          name: calcom
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: calcom-secret
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: calcom-postgresql-app
                key: uri
          - name: DATABASE_DIRECT_URL
            valueFrom:
              secretKeyRef:
                name: calcom-postgresql-app
                key: uri
          - name: SAML_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: calcom-postgresql-app
                key: uri
          - name: SAML_ADMINS
            value: "ryzen@ryzen.me"
          - name: NEXT_PUBLIC_WEBAPP_URL
            value: https://cal.ryzen.me
          - name: ALLOWED_HOSTNAMES
            value: '"cal.ryzen.me","localhost:3000"'
      restartPolicy: Always