apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
  name: calcom
  namespace: calcom
spec:
  ingressClassName: traefik
  rules:
    - host: cal.ryzen.me
      http:
        paths:
          - path: /
            pathType: prefix
            backend:
              service:
                name: calcom
                port:
                  number: 3000
  tls:
    - hosts:
        - cal.ryzen.me
      secretName: calcom-tls