apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radicale
  namespace: radicale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cal.ryzen.me`)
      kind: Rule
      middlewares:
        - name: radicale-middleware
      services:
        - name: radicale 
          port: 5232
  tls:
    secretName: radicale-tls