apiVersion: v1
kind: Service
metadata:
  name: radicale-auth
  namespace: radicale
  labels:
    app: radicale-auth
spec:
  type: ClusterIP
  selector:
    app: radicale-auth
  ports:
  - name: http
    port: 4181