apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radicale-proxy
  name: radicale-proxy
  namespace: radicale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radicale-proxy
  template:
    metadata:
      labels:
        app: radicale-proxy
    spec:
      containers:
      - name: radicale-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        args:
          - --provider=keycloak-oidc
          - --email-domain=*
          - --upstream=file:///dev/null
          - --http-address=0.0.0.0:4180
          - --oidc-issuer-url=https://auth.ryzen.me/realms/public
          - --reverse-proxy=true
          - --set-xauthrequest=true
          - --pass-user-headers=true
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: radicale
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: radicale-proxy-secret
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: radicale-proxy-secret
                key: cookie-secret
        ports:
          - containerPort: 4180
            name: http
