apiVersion: v1
kind: Service
metadata:
  name: radicale-proxy
  namespace: radicale
  labels:
    app: radicale-proxy
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: radicale-proxy