apiVersion: v1
kind: Service
metadata:
  name: radicale-proxy
  namespace: radicale
  labels:
    app: radicale-proxy
spec:
  type: ClusterIP
  selector:
    app: radicale-proxy
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181